# fly.toml app configuration file generated for cstillas-muddy-field-6842 on 2024-05-10T08:39:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tomaszborowiec'
primary_region = 'arn'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  RAILS_STORAGE = '/data/storage'

[[mounts]]
  source = 'myapp_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
