# fly.toml app configuration file generated for scaffoldlist on 2023-08-21T14:27:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cstillas"
primary_region = "arn"
console_command = "/rails/bin/rails console"



[deploy]
  release_command = "./bin/rails db:prepare"

[env]
  RAILS_STORAGE = "/data/storage"

[[mounts]]
  source = "myapp_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
