# fly.toml app configuration file generated for scaffoldlistv2 on 2023-07-11T12:40:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scaffoldlistv2"
primary_region = "waw"
console_command = "/rails/bin/rails console"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

  [mounts]
source="myapp_data"
destination="/data"

